### ISSUE TITLE
handle not ready errors

### ISSUE THREAD

**Issue by bovine3dom** [bovine3dom/H3-MON#8]
```
error: Uncaught (in promise) InvalidStateError: readyState not OPEN
                socket.send("file changed")
                       ^
    at WebSocket.send (ext:deno_websocket/01_websocket.js:326:13)
    at watchcsv (file:///home/olie/projects/H3-MON/srv/watcher.js:32:24)
    at eventLoopTick (ext:core/01_core.js:168:7)
error Command failed with exit code 1.
```

(i think real root cause of this is that the file triggers too many "updated" events, should probably buffer them)

**Comment by bovine3dom** [comment]
done in 90a4e18 probably
